# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
u1 = User.create(email: 'ripe@gmail.com', password: 'password')
u2 = User.create(email: 'thejamaicandave@gmail.com', password: 'password')
u3 = User.create(email: 'arthur@aa.io', password: 'password')
a1 = Author.create(name: 'Mark Twain')
a2 = Author.create(name: 'William Faulkner')
a3 = Author.create(name: 'Harper Lee')

# b1 = a1.books.create(title: 'The Adventures of Huckleberry Finn', image: File.new("#{Rails.root}/app/assets/images/author.jpg"))
# b1 = a1.books.create(title: 'The Adventures of Huckleberry Finn')
# b2 = a1.books.create(title: 'The Adventures of Tom Sawyer')
# b3 = a1.books.create(title: 'The Prince and the Pauper ')
# b4 = a2.books.create(title: 'The Sound and the Fury')
# b5 = a2.books.create(title: 'As I Lay Dying')
# b6 = a2.books.create(title: 'Light in August')
b1 = a1.books.create(title: 'The Adventures of Huckleberry Finn', image: File.new("#{Rails.root}/app/assets/images/huckleberry_finn.jpg"))
b2 = a1.books.create(title: 'The Adventures of Tom Sawyer', image: File.new("#{Rails.root}/app/assets/images/tom_sawyer.jpg"))
b3 = a1.books.create(title: 'The Prince and the Pauper', image: File.new("#{Rails.root}/app/assets/images/prince_and_pauper.jpg"))
b4 = a2.books.create(title: 'The Sound and the Fury', image: File.new("#{Rails.root}/app/assets/images/sound_and_fury.jpg"))
b5 = a2.books.create(title: 'As I Lay Dying', image: File.new("#{Rails.root}/app/assets/images/lay_dying.jpg"))
b6 = a2.books.create(title: 'Light in August', image: File.new("#{Rails.root}/app/assets/images/light_in_august.jpg"))
# b7 = a3.books.create(title: 'To Kill a Mockingbird ')
# b8 = a3.books.create(title: 'Go Set a Watchman ')

b1.reviews.create(content: 'A good book', user_id: 1, rating: 1)
b1.reviews.create(content: 'A great book, too', user_id: 2, rating: 2)
b1.reviews.create(content: 'A fantastic book', user_id: 3, rating: 3)
b2.reviews.create(content: 'A good book', user_id: 1, rating: 4)
b2.reviews.create(content: 'A great book, too', user_id: 2, rating: 5)
b2.reviews.create(content: 'A fantastic book', user_id: 3, rating: 1)
b3.reviews.create(content: 'A good book', user_id: 1, rating: 2)
b3.reviews.create(content: 'A great book, too', user_id: 2, rating: 3)
b3.reviews.create(content: 'A fantastic book', user_id: 3, rating: 4)
b4.reviews.create(content: 'A good book', user_id: 1, rating: 5)
b4.reviews.create(content: 'A great book, too', user_id: 2, rating: 1)
b4.reviews.create(content: 'A fantastic book', user_id: 3, rating: 2)
b5.reviews.create(content: 'A good book', user_id: 1, rating: 3)
b5.reviews.create(content: 'A great book, too', user_id: 2, rating: 4)
b5.reviews.create(content: 'A fantastic book', user_id: 3, rating: 5)
b6.reviews.create(content: 'A good book', user_id: 1, rating: 1)
b6.reviews.create(content: 'A great book, too', user_id: 2, rating: 2)
b6.reviews.create(content: 'A fantastic book', user_id: 3, rating: 3)

# b1.ratings.create(stars: 4, user_id: 1)
# b1.ratings.create(stars: 3, user_id: 2)
s1 = u1.shelves.create(category: "to_read", name: "To Read")
s2 = u1.shelves.create(category: "reading", name: "Reading")
s3 = u1.shelves.create(category: "read", name: "Read")
s4 = u1.shelves.create(category: "custom", name: "Custom 1")
s5 = u2.shelves.create(category: "to_read", name: "To Read")
s6 = u2.shelves.create(category: "reading", name: "Reading")
s7 = u2.shelves.create(category: "read", name: "Read")
s8 = u2.shelves.create(category: "custom", name: "Custom 1")
s9 = u3.shelves.create(category: "to_read", name: "To Read")
s10 = u3.shelves.create(category: "reading", name: "Reading")
s11 = u3.shelves.create(category: "read", name: "Read")
s12 = u3.shelves.create(category: "custom", name: "Custom 1")

s1.shelvings.create(book_id: 1)
s1.shelvings.create(book_id: 3)
s2.shelvings.create(book_id: 2)
s2.shelvings.create(book_id: 4)
s3.shelvings.create(book_id: 5)
s3.shelvings.create(book_id: 6)
s4.shelvings.create(book_id: 5)
s4.shelvings.create(book_id: 6)
